### ISSUE TITLE
DSC doesn't recognize Log4j patch installed for server

### ISSUE THREAD

**Issue by rlesperance** [Esri/arcgis-powershell-dsc#394] opened 2022-05-05 00:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version
* 3.3.2

### Affected Resource(s)

* ArcGIS_Server

### Configuration Files

[BaseDeployment_MultiMachine.zip](https://github.com/Esri/arcgis-powershell-dsc/files/8628152/BaseDeployment_MultiMachine.zip)

### Expected Behavior

DSC should recognize that log4j patch is already installed and skip. 

### Actual Behavior

Verbose records show DSC not seeing the patch and then tries to install it again.  Already confirmed before running the script that the patch was already installed. 
> Patch not installed - installing
5/4/2022 2:03:26 PM: [COH-GIS-12]:                            [[ArcGIS_InstallPatch]ServerInstallPatch] /update "C:\Install\ArcGIS_Enterprise_1091\ArcGIS-1091-S-Log4j-PatchB.msp" /quiet
5/4/2022 2:06:12 PM: [COH-GIS-11]:                            [[ArcGIS_InstallPatch]ServerInstallPatch] Patch Installation successful.

### Steps to Reproduce

Running the same JSON again with any alteration, not necessarily the patch section.  In this latest run I was updating the CA certs with new ones. 

### Important Factoids

Nutanix VM on-prem.  Servers are all 2 machine sites.  Federated with a single machine Portal.

**Comment by cameronkroeker** [comment] 2022-05-05 18:37
Hi @rlesperance,

Looks like the issue is that the `ArcGIS-1091-S-Log4j-PatchB.msp` file contains an incorrect QFE ID. It wasn't updated to contain the correct QFE ID that gets placed within the Windows registry:

<img width="954" alt="Screen Shot 2022-05-05 at 11 03 05 AM" src="https://user-images.githubusercontent.com/48299621/166993026-1aa5132e-7fbd-4d2b-a883-86b0817fc4fd.png">

The ArcGIS Module will first extract the QFE ID from the patch .msp file, and compare it against the registry to see if the patch has already been installed. If the values match then installation is skipped, however if they don't match then the patch gets installed. In the instances where the QFE ID within the msp file is missing or incorrect, then the patches get installed every time even though it may already exist.

In this case the QFE ID in the `ArcGIS-1091-S-Log4j-PatchB.msp` is `S-1091-P-715`, however the value defined in the registry `HKEY_LOCAL_MACHINE\SOFTWARE\ESRI\Server10.9\Updates\10.9_1_13` is `S-1091-P-715B`, therefore since they don't match the patch gets re-installed.

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment] 2022-05-11 17:27
Closing due to this not being an issue with dsc but rather being a technical limitation with the ArcGIS-1091-S-Log4j-PatchB.msp file containing incorrect QFE ID.

**Closed by cameronkroeker** 2022-05-11 17:27 UTC
