### ISSUE TITLE
Error "Invalid values for role and/or user license type parameters" when using account_publisher

### ISSUE THREAD

**Issue by BrendanEsri** [Esri/arcgis-powershell-dsc#269] opened 2020-05-15 20:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.0.1

### Affected Resource(s)

* ArcGIS_Portal 10.8

### Configuration Files

**INCORRECT**

```
"DefaultRoleForUser": "account_publisher",
```

vs.

**CORRECT**
```
"DefaultRoleForUser": "org_publisher",
```

### Expected Behavior

It works and applies the role

### Actual Behavior

it fails with the error:
Trace-DSCJob : PowerShell DSC resource ArcGIS_Portal  failed to execute Set-TargetResource functionality with error message: [Error] - Set-PortalUserDefaults Response:-
Invalid values for role and/or user license type parameters.

### Steps to Reproduce

Use the first code where it references "account_publisher" 

To get it to work use the "org_publisher"

### References

The REST API documentation references these:
Values: org_admin | org_publisher | org_user | iBBBBBBBBBBBBBBB (Data Editor)| iAAAAAAAAAAAAAAA (Viewer)
--https://developers.arcgis.com/rest/enterprise-administration/portal/create-user.htm

Whereas the GitHub docs reference this:
Values: account_user | account_publisher | account_admin | custom_role_ID
--https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

**Comment by Nickolaitc** [comment] 2020-05-15 21:06
REST API documentation: https://developers.arcgis.com/rest/enterprise-administration/portal/create-user.htm

**Comment by cameronkroeker** [comment] 2020-05-15 22:19
Thanks @BrendanEsri and @Nickolaitc. This is indeed a bit odd/confusing as the following documentation shows:

`defaultRoleForUser: Values: account_user | account_publisher | <custom role ID>`

https://developers.arcgis.com/rest/enterprise-administration/portal/update-security-configuration.htm

Which version of ArcGIS Enteprise was this reproduced with? 

The reason I ask is at _10.8, the default user role is no longer set through the Portal Admin API. The default role for new members can now be set from the New Member Defaults tab in the Organization Settings of the portal or through the Set User Default Settings operation in the Sharing API._

So the version of portal very well could be key.

**Comment by BrendanEsri** [comment] 2020-05-15 22:22
It was repro'd with 10.8

**Comment by cameronkroeker** [comment] 2020-05-18 19:57
This is a non issue. Verified that the following values work do work in 10.8:

`defaultRoleForUser: Values: account_user | account_publisher | <custom role ID>`

However, the error was caused by using an incompatible DefaultUserLicenseTypeIdForUser.

**DefaultUserLicenseTypeIdForUser** - This property sets the default user type assigned to users during account creation and when creating built-in accounts. **These user types must be compatible with the defaultRoleForUser that has been specified.** Values: fieldWorkerUT | GISProfessionalStdUT | GISProfessionalBasicUT | GISProfessionalAdvUT | creatorUT | editorUT | viewerUT

**Closed by cameronkroeker** 2020-05-18 19:57 UTC
