### ISSUE TITLE
IIS/IWA EnableAutomaticAccountCreation not set correctly (10.7.1 using PSDSC 2.1.1) - default user type id must be specified

### ISSUE THREAD

**Issue by pfoppe** [Esri/arcgis-powershell-dsc#208] opened 2019-10-09 15:55 UTC
Hello, 

I recently deployed a new base v10.7.1 ArcGIS Enterprise on 1 machine (IIS, 2 web-adaptors, portal, server, datastore) using the "Configure-ArcGIS" <json file> InstallLicenseConfigure command.  This environment is setup with IIS web-tier authentication and the the automatic account creation was specified as "true".  See attached (redacted) .json file

Overall the execution appeared successful (all products installed, licensed, federated, hosted, etc), but users were unable to login the first time.  Investigation into the environment showed that the "enableAutomaticAccountCreation" was set to false (https://server.domain/portal/portaladmin/security/config).  I was able to manually set it to true.

Looking through the logs... this seems to have failed.  Per the **ArcGISConfigure-<date_time>-PM-Verbose.txt:**

> [MACHINE]: [[ArcGIS_Portal]PortalMACHINE] Set-PortalSecurityConfig Response:- @{code=500; message=A default user type id must be specified to enable automatic account creation for your Enterprise portal.; details=} @{error=}

The Esri Docs at v10.7.1 also state that a default user type needs to be set - https://enterprise.arcgis.com/en/portal/latest/administer/windows/automatic-registration-of-enterprise-accounts.htm

Thoughts?  We've been successful doing 10.6.1 to 10.7.1 upgrades so far, just seemed to fail with a default 10.7.1 install.  

Thanks!

[redacted_json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/3708308/redacted_json.txt)

**Comment by pfoppe** [comment] 2019-11-13 16:42
Hello, we recently deployed a new system and ran into this issue again.  Any update/feedback?

**Comment by cameronkroeker** [comment] 2019-11-13 19:41
Hi @pfoppe,

I believe the issue is that the "defaultRoleForUser" and "defaultUserTypeIdForUser" parameters are not being passed in the POST request when setting "enableAutomaticAccountCreation" to true. Perhaps the upgrades are succeeding because those values were/are already set/present prior to the upgrade.

**Comment by pfoppe** [comment] 2019-11-13 21:11
Hi @cameronkroeker 

Thanks for the response.  Looking at this specific environment, I can confirm the portal "DefaultUserTypeIdForUser" was set to "creatorUT".  The json file does have the "PortalLicenseUserType" set to "Creator" which I think is what set this.  

Its been over a month since we completed this install, but I'm pretty sure that got set by the PSDSC execution.  

Do you think this is a bug?  Anything else I can do to correct this for future deployments (like a missing setting)?  Thanks

**Comment by cameronkroeker** [comment] 2019-12-12 23:26
@pfoppe Apologies for the long delay, but this issue will be addressed in the next release.

**Comment by pfoppe** [comment] 2019-12-12 23:53
Great... thanks!!

**Comment by cameronkroeker** [comment] 2020-02-28 17:20
@pfoppe,

We have addressed this issue in the latest release, v3.0.0:

https://github.com/Esri/arcgis-powershell-dsc/releases

**Sample Config:**
https://github.com/Esri/arcgis-powershell-dsc/blob/7d365cb94b9ae351797af2cce582dd8b811f1a49/SampleConfigs/v3/Base%20Deployment/BaseDeployment-SingleMachine.json#L111

**Closed by cameronkroeker** 2020-02-28 17:20 UTC
Labels: JSON Sample Update, Wiki Update, bug
