### ISSUE TITLE
Problem with federation

### ISSUE THREAD

**Issue by jbiendara** [Esri/arcgis-powershell-dsc#94] opened 2018-09-06 08:33 UTC
Hello,
I have two configuration files to set up a three machine environment. The only difference between the two configuration files are the “ssl per node” sections in the “AllNodes” part (one file with, one without this sections). (Still trying to get the server certificate installed on the portal machine and the root certificate on portal and server machines. 😊)

With ssl sections
[WithSSLSections.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2356182/WithSSLSections.txt)

Without ssl sections
[WithoutSSLSections.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2356184/WithoutSSLSections.txt)

In my opinion, both files should run without errors for the same (i. e. physically identical) environment. Running the configuration file WITHOUT the “ssl per node” sections, the federation of sever (vsdev2371) with portal (vsdev2370) works fine

[Okay_WithoutSSLSections.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2356191/Okay_WithoutSSLSections.txt)
 
The token for the federation is requested from the portal machine vsdev2370.

But, running the configuration file WITH the “ssl per node” sections, the routine tries to get a portal token from the server machine vsdev2371:

[Error_WithSSLSections.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2356196/Error_WithSSLSections.txt)

Any idea, why the configuration file WITH the “ssl per node” sections is requesting a token from the wrong server machine?

Thank you very much, best regards,
Jürgen

**Comment by spitzerr** [comment] 2018-09-06 13:51
Hi @jbiendara,

your config with-ssl is missing some square-brackets. This part:

``` 
"SslRootOrIntermediate" : {
			"Alias":	"esri-root",
			"Path":		"C:\\data\\ArcGIS_Configuration\\Certificate\\esri-root.cer"
					 },

```

should be:
``` 
"SslRootOrIntermediate" : [{
			"Alias":	"esri-root",
			"Path":		"C:\\data\\ArcGIS_Configuration\\Certificate\\esri-root.cer"
					}],

```

Maybe this fixes also #90 Q5

Cheers,
Rainer

**Comment by jbiendara** [comment] 2018-09-07 08:27
Hi Rainer,

Unfortunately, adding the extra square brackets didn't change anything.

As soon as I add the “ssl per node” sections to the “AllNodes” part the procedure gets confused. Okay, the node ssl certificates get installed as well as does the root certificate.

But when it comes to federate the server (vsdev2371) with the portal (vsdev2370) the procedure requires a token from the server (vsdev2371), not from the portal (vsdev2370). The federation times out.

Without the “ssl per node” sections in the “AllNodes” part the procedure requires the token for the federation correctly from the portal (vsdev2370), the federation is done in seconds.

Why does the procedure gets mixed up?

Btw: I thought that the square brackets only designate the sections that need to be configured/filled in with the values of the environment or sections that are optional. Now it seems that they also do have a functional significance. Can you help me, what the (functional) difference between the square and the curly brackets is and what they both are used for in the context of the configuration scripts?

Thank you very much, best regards,
Jürgen

**Comment by spitzerr** [comment] 2018-09-07 09:02
Hi,

**About the bracketts**: The config is written in json-notation. Square-Bracketts are used for Arrays over there. You can see some more Information About Syntax e.g. here: http://www.json.org/

At the example configuration files there are also some square-bracketts inside of Quotation marks. These are meant as optional/filled Information which hast to be changed for use.

---
> As soon as I add the “ssl per node” sections to the “AllNodes” part the procedure gets confused. Okay, the node ssl certificates get installed as well as does the root certificate.

For clarification: Are both certificates now installed in Portal Cert-Store?

---
> Why does the procedure gets mixed up?

This could be a bug. On our Tests we had all WebAdaptors on the same machine and everything worked fine. Could your verify this?

**Comment by shailesh91** [comment] 2018-09-07 22:27
@jbiendara @spitzerr 
Call for federation is made on server web adaptor. So when the web adaptors are on different machines the Portal WebAdaptor endpoint is wrongly inferred. This line is the cause of the error.
https://github.com/Esri/arcgis-powershell-dsc/blob/bfae4eb747903d76d640d9edfb5f67daf87d15e3/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L1664

To get around the error use the following configuation.
[WithSSLSections.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2362681/WithSSLSections.txt)

Ps. in this config, when a portal and portal webadaptor is on the same, the certificate is not installed  Portal Cert-Store. It is installed in Machine Cert-Store.

**Comment by shailesh91** [comment] 2018-09-13 21:49
@jbiendara @spitzerr Pull request #95 should solve this bug. You can fork the PR and try it out.

**Comment by spitzerr** [comment] 2018-09-19 12:37
@shailesh91 from my perspective there is an additional timing Problem:
webadaptor waits until ArcGIS_Portal is finished to Register Portal in WA:
https://github.com/Esri/arcgis-powershell-dsc/blob/bfae4eb747903d76d640d9edfb5f67daf87d15e3/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L1474-L1488
After ArcGIS_Portal is finished ArcGIS_Portal_TLS is executed:
https://github.com/Esri/arcgis-powershell-dsc/blob/bfae4eb747903d76d640d9edfb5f67daf87d15e3/Modules/ArcGIS/Configuration/ArcGISConfigure.ps1#L1006-L1038
As ArcGIS_Portal_TLS installs a new Cert in Portal Cert-Store the Portal-WebServer is restarted. At the same time ArcGIS WebAdaptor tries to get a token and Fails...

I'm not sure how to come around this. Maybe you have an idea.

**Comment by shailesh91** [comment] 2018-09-19 17:10
@spitzerr I will try to repro this issue (Can you send the config file you are using). I have a solution in mind for wmf5 that requires minimal change. But I am not sure how I will get this working in wmf4. Need to brainstorm a little more that.

**Comment by spitzerr** [comment] 2018-09-19 17:55
@shailesh91 please find attached the config which Fails on our site. As it is a racing condition I think it's hard to reproduce anyway.
Hope you can find a fix

[config.json](https://github.com/Esri/arcgis-powershell-dsc/files/2398185/config.json.txt)

**Comment by nshampur** [comment] 2018-09-19 17:57
adding retries to ArcGIS WebAdaptor when it attempts to get a token and the Portal is restarting might be a good fix.

**Comment by shailesh91** [comment] 2018-09-19 18:11
@spitzerr just an FYI, support for global certs used is going away with the latest PR. You will have to use the node level certs.
@nshampur Will give the retry solution a try.

**Comment by shailesh91** [comment] 2018-09-24 17:54
Closing the issue. Please open again if you have any further issues.

**Closed by shailesh91** 2018-09-24 17:54 UTC
Labels: bug
