### ISSUE TITLE
Dual Machine Upgrade Federated/Hosting Server Web Adaptor Configure fails

### ISSUE THREAD

**Issue by l84tahoe** [Esri/arcgis-powershell-dsc#98] opened 2018-09-26 16:10 UTC
We are trying to upgrade an existing ArcGIS Enterprise (10.6 to 10.6.1) on two machines in our development environment and run into a specific error when Powersehll DSC tries to configure the federated hosting server web adaptor: 

`[]PowerShell DSC resource ArcGIS_WebAdaptor  failed to execute Test-TargetResource functionality with error message: PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc.
[]The SendConfigurationApply function did not succeed.
`
Since this web adaptor doesn't get configured correctly we are having a hard time trying to get all three components to link. 

We also are unable to get the datastore to configure even though the script said it was successful. I believe it's because the web adaptor for the server failed. 

In the log of the datastore upgrade we see this:

```
[Machine2]:                            [[File]CreateUpgradeFile] The system cannot find the file specified.
[Machine2]:                            [[File]CreateUpgradeFile] The related file/directory is: C:\Program Files\ArcGIS\DataStore\etc\upgrade.txt.
[Machine2]: LCM:  [ End    Test     ]  [[File]CreateUpgradeFile]  in 0.0470 seconds.
[Machine2]: LCM:  [ Start  Set      ]  [[File]CreateUpgradeFile]
[Machine2]:                            [[File]CreateUpgradeFile] The system cannot find the file specified.
[Machine2]:                            [[File]CreateUpgradeFile] The related file/directory is: C:\Program Files\ArcGIS\DataStore\etc\upgrade.txt.
[Machine2]:                            [[File]CreateUpgradeFile] C:\Program Files\ArcGIS\DataStore\etc\upgrade.txt was successfully created.
[Machine2]: LCM:  [ End    Set      ]  [[File]CreateUpgradeFile]  in 0.0000 seconds.
```
and we can't find the file referenced above.

We also see this a few lines below:
```
[Machine2]:                            [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start] [WARNING] Stopping Server :- Cannot validate argument on parameter 'Message'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

Another odd error we see is that Powershell DSC tried to install datastore on the other machine and fails because the installation file is not on that machine. After that error Powershell DSC then tries to upgrade the correct machine. Here is the error:
```
[]PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: D:\InstallationFiles\1061\ArcGIS_DataStore_Windows_1061_163980.exe is not found or inaccessible
[]The SendConfigurationApply function did not succeed.
```

Here is our configuration file:
```
{
    "AllNodes":  [
                     {
                         "NodeName":  "Machine1",
                         "Role":  [
                                      "PortalWebAdaptor",
                                      "ServerWebAdaptor",
                                      "Portal",
                                      "Server"
                                  ]
                     },
                     {
                         "NodeName":   "Machine2",
                         "DataStoreTypes":  [ 
                                              "Relational"
                                            ],
                         "Role":  [
                                      "DataStore",
				      "TileCache"
                                  ]
                     }
                 ],
    "ConfigData":  {
                       "Version":  "10.6.1",
		       "OldVersion":  "10.6",
                       "ServerContext":  "server",
                       "PortalContext":  "portal",
                       "ServerRole": "GeneralPurposeServer",
                       "Credentials":  {
                                           "PrimarySiteAdmin":  {
                                                                  "UserName":  "Admin",
                                                                  "Email":  "fake@email.com",
                                                                  "Password":  "Password"
                                                                },
                                           "ServiceAccount":  {
                                                                  "Password":  "Password",
                                                                  "UserName":  "domain\\Admin",
                                                                  "IsDomainAccount": true
                                                              },
                                           "ADServiceUser":  {
                                                                  "Password":  "Password",
                                                                  "UserName":  "domain\\Admin"
                                                              }
				  
                                       },
                       "Server":  {
                                      "LicenseFilePath":   "D:\\InstallationFiles\\1061\\ArcGISGISServerStandard_ArcGISServer_621558.prvc",
                                      "Installer":  {
                                                        "Path":  "D:\\InstallationFiles\\1061\\ArcGIS_Server_Windows_1061_163968.exe",
                                                        "InstallDir":  "C:\\Program Files\\ArcGIS\\Server",
                                                        "InstallDirPython":  "C:\\Python27"
                                                    },
                                      "ServerDirectoriesRootLocation":  "D:\\arcgisserver\\directories",
                                      "ConfigStoreLocation":  "D:\\arcgisserver\\config-store"
                                  },
                       "Portal":  {
                                      "LicenseFilePath": "D:\\InstallationFiles\\1061\\Level1NamedUsersPortalforArcGIS_621975.prvc",
                                      "Installer":  {
                                                        "Path":  "D:\\InstallationFiles\\1061\\Portal_for_ArcGIS_Windows_1061_163979.exe",
                                                        "InstallDir": "C:\\Program Files\\ArcGIS\\Portal",
                                                        "ContentDir": "D:\\"
                                                    },
                                      "ContentDirectoryLocation":  "D:\\arcgisportal\\content"
                                  },
                       "DataStore":  {
                                         "ContentDirectoryLocation":  "D:\\arcgisdatastore",
                                         "Installer":  {
                                                           "Path":  "D:\\InstallationFiles\\1061\\ArcGIS_DataStore_Windows_1061_163980.exe",
                                                           "InstallDir":  "C:\\Program Files\\ArcGIS\\DataStore"
                                                       }
                                     },
                       "WebAdaptor":  {
                                          "AdminAccessEnabled":  true,
                                          "Installer":  {
                                                            "Path":  "D:\\InstallationFiles\\1061\\Web_Adaptor_for_Microsoft_IIS_1061_163981.exe"
                                                        }
                                      }
                   }
}
```

**Comment by shailesh91** [comment] 2018-09-26 16:27
@l84tahoe One of the prereqs of Running Powershell DSC is that the installation files should be accessible on the target machines (Either installation files are placed on a file share accessible the local system account of the target machine or local to the target machine placed as specified in the JSON config file). 
As for the web adaptor when you run the upgrade next time can you please run it in with -DebugSwitch in the configure command. This will provide a little more verbosity about the sequence of steps that led to that error.

**Comment by l84tahoe** [comment] 2018-09-26 16:32
@shailesh91 The files are on a local drive ( D:\ ) of each machine. The issue with that error is that I never said Machine1 should have a datastore but the script thinks it should have it.

I will rerun using the -DebugSwitch right now.

**Comment by shailesh91** [comment] 2018-09-26 16:39
I don't think the error was on machine1 as the error doesn't specify a machine name. It would be great to have the logs generated though.

**Comment by l84tahoe** [comment] 2018-09-26 16:42
Sorry I didn't make it clearer earlier. Here is the Powershell output showing Powershell trying to install on Machine1 when it shouldn't:
```
Starting DSC Job:- DataStoreUpgradeInstall
VERBOSE: Time taken for configuration job to complete is 0.012 seconds
[Machine1]: LCM:  [ Start  Set      ]
[Machine1]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine1]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine1]: LCM:  [ End    Test     ]  [[ArcGIS_Install]DataStoreUpgrade]  in 0.8830 seconds.
[Machine1]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine1]: LCM:  [ End    Set      ]  [[ArcGIS_Install]DataStoreUpgrade]  in 0.0280 seconds.
[Machine1]: LCM:  [ End    Set      ]
[]PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: D:\InstallationFiles\1061\ArcGIS_DataStore_Windows_1061_163980.exe is not found or inaccessible
[]The SendConfigurationApply function did not succeed.
[Machine2]: LCM:  [ Start  Set      ]
[Machine2]: LCM:  [ Start  Resource ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine2]: LCM:  [ Start  Test     ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine2]: LCM:  [ End    Test     ]  [[ArcGIS_Install]DataStoreUpgrade]  in 1.2500 seconds.
[Machine2]: LCM:  [ Start  Set      ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine2]: LCM:  [ End    Set      ]  [[ArcGIS_Install]DataStoreUpgrade]  in 323.0460 seconds.
[Machine2]: LCM:  [ End    Resource ]  [[ArcGIS_Install]DataStoreUpgrade]
[Machine2]: LCM:  [ Start  Resource ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Stop]
[Machine2]: LCM:  [ Start  Test     ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Stop]
[Machine2]: LCM:  [ End    Test     ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Stop]  in 0.2190 seconds.
[Machine2]: LCM:  [ Start  Set      ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Stop]
[Machine2]: LCM:  [ End    Set      ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Stop]  in 11.2170 seconds.
[Machine2]: LCM:  [ End    Resource ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Stop]
[Machine2]: LCM:  [ Start  Resource ]  [[File]CreateUpgradeFile]
[Machine2]: LCM:  [ Start  Test     ]  [[File]CreateUpgradeFile]
[Machine2]: LCM:  [ End    Test     ]  [[File]CreateUpgradeFile]  in 0.0470 seconds.
[Machine2]: LCM:  [ Start  Set      ]  [[File]CreateUpgradeFile]
[Machine2]: LCM:  [ End    Set      ]  [[File]CreateUpgradeFile]  in 0.0000 seconds.
[Machine2]: LCM:  [ End    Resource ]  [[File]CreateUpgradeFile]
[Machine2]: LCM:  [ Start  Resource ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start]
[Machine2]: LCM:  [ Start  Test     ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start]
[Machine2]: LCM:  [ End    Test     ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start]  in 0.0160 seconds.
[Machine2]: LCM:  [ Start  Set      ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start]
[Machine2]: LCM:  [ End    Set      ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start]  in 0.1980 seconds.
[Machine2]: LCM:  [ End    Resource ]  [[ArcGIS_WindowsService]ArcGIS_DataStore_Service_Start]
[Machine2]: LCM:  [ End    Set      ]
[Machine2]: LCM:  [ End    Set      ]    in  337.2630 seconds.
```

**Comment by shailesh91** [comment] 2018-09-26 16:51
@l84tahoe it is a bug. I can provide you a local patch just in case you are testing right now.

**Comment by l84tahoe** [comment] 2018-09-26 16:53
@shailesh91 I am. Will this patch also fix the webadaptor issue?

**Comment by shailesh91** [comment] 2018-09-26 16:55
@l84tahoe I am still unclear on the web adaptor issue. I need more logs to tell what might be going wrong.

**Comment by l84tahoe** [comment] 2018-09-26 17:00
Sorry, here is the verbose log of the incident:
```
[Machine1]: LCM:  [ Start  Resource ]  [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com]
[Machine1]: LCM:  [ Start  Test     ]  [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com]
[Machine1]: LCM:  [ End    Test     ]  [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com]  in 0.9290 seconds.
[Machine1]: LCM:  [ Start  Set      ]  [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com]
[Machine1]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com] https://Machine1.domain.com/portal/webadaptor
[Machine1]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com] Executing C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe with arguments /m portal /w https://Machine1.domain.com/portal/webadaptor /g https://Machine1.domain.com:7443 /u Admin /p Password
[Machine1]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com] C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe /m portal /w https://Machine1.domain.com/portal/webadaptor /g https://Machine1.domain.com:7443 /u Admin /p Password
[Machine1]:                            [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com] Output of execution:- Unable to register with Portal. The remote server returned an error: (401) Unauthorized.
[Machine1]: LCM:  [ End    Set      ]  [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com]  in 5.9460 seconds.
[Machine1]: LCM:  [ End    Resource ]  [[ArcGIS_WebAdaptor]ConfigurePortal-Machine1.domain.com]
[Machine1]: LCM:  [ End    Set      ]
[Machine1]: LCM:  [ End    Set      ]    in  100.6120 seconds.
```

The admin account is a built in account and not a domain account.

**Comment by shailesh91** [comment] 2018-09-26 17:08
@l84tahoe can you try running this command for cmd 
```
C:\Program Files (x86)\Common Files\ArcGIS\WebAdaptor\IIS\Tools\ConfigureWebAdaptor.exe /m portal /w https://Machine1.domain.com/portal/webadaptor /g https://Machine1.domain.com:7443 /u Admin /p Password
```
Another thing you can try is going to "https://Machine1.domain.com:7443/arcgis/portaladmin" and try logging in.

**Comment by l84tahoe** [comment] 2018-09-26 17:34
@shailesh91 I am able to log in using the built in admin account through `/portaladmin` When I use the command prompt I get `Unable to register with Portal. The remote server returned an error: (401) Unauthorized.` BTW we are using IWA throughout the enterprise.

**Comment by shailesh91** [comment] 2018-09-26 19:48
@l84tahoe Can you try registering web adaptor through the UI, just to check if we get the same error or is something to do with configure utility.

**Comment by l84tahoe** [comment] 2018-09-26 19:51
@shailesh91 I am waiting for the upgrade with `-DebugSwitch` to complete still, but in a previous attempt I was able to register the web adaptor to Portal using the web interface using the same credentials in the utility.

**Comment by l84tahoe** [comment] 2018-09-26 20:10
@shailesh91 The portal web adaptor config failed again. Same 401 error. Server web adaptor now fails as well with this error: 
```
[]PowerShell DSC resource ArcGIS_WebAdaptor  failed to execute Test-TargetResource functionality with error message: PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc.
[]The SendConfigurationApply function did not succeed.
```

And after copying your updated `ArcGIS.psm1` to the ArcGIS Module in all machines I get this error when it tries to update datastore:

```
Start-DscConfiguration : The computer name was not specified and the configuration directory does not have any configuration files.
At C:\Users\rmalhoski\Documents\WindowsPowerShell\Modules\ArcGIS\1.1.0\ArcGIS.psm1:214 char:16
+ ...      $Job = Start-DscConfiguration -Path ".\$($ConfigurationName)" -F ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-DscConfiguration], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigurationCommand
```

**Comment by shailesh91** [comment] 2018-09-26 20:29
@l84tahoe Can you try with this file. 
https://raw.githubusercontent.com/Esri/arcgis-powershell-dsc/a03869c38ba5826b619937cd6ac369f043f4d75e/Modules/ArcGIS/ArcGIS.psm1

And if possible please provide verbose logs. That will be very helpful.

**Comment by shailesh91** [comment] 2018-09-26 20:49
@l84tahoe can email me at **shgoel@esri.com** . I can help you to debug the problems on skype.

**Comment by shailesh91** [comment] 2019-02-19 19:56
The issue was fixed in 1.1.3 and 1.1.4 release. Closing the issue. Please reopen it still persists.

**Closed by shailesh91** 2019-02-19 19:56 UTC
Labels: bug

**Comment by scma-esrich** [comment] 2020-04-09 10:13
@shailesh91, maybe the Web Adaptor-part of the bug came back with the current release (WELCHE VERSION MATTHIAS?) of the DSC-module.

Our customer is trying to upgrade a multi-machine base-deployment from 10.7.1 to 10.8 and triggers the following error:
```
Die PowerShell DSC-Ressource "ArcGIS_WebAdaptor" konnte die Funktion "Test-TargetResource" nicht ausführen. Fehlermeldung: "Die PowerShell-Konfiguration für den gewünschten Zustand unterstützt die Befehlsausführung in einem interaktiven Modus nicht. Stellen Sie sicher, dass der zugrunde liegende Befehl keine Benutzereingabe anfordert wie einen fehlenden erforderlichen Parameter oder eine Bestätigung." 
Die Funktion 'SendConfigurationApply' war nicht erfolgreich.
```
The server-OS is German, hence the error-messages are also in German. However, the main-part of the error-message translates exactly to:
```[]PowerShell DSC resource ArcGIS_WebAdaptor failed to execute Test-TargetResource functionality with error message: PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc. []The SendConfigurationApply function did not succeed.```

This is the corresponding Verbose-log-statement:
```
Vorgang "CIM-Methode aufrufen" mit den folgenden Parametern durchführen, "'methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration".
Vom Computer 'JumpHost' mit Benutzer-SID 'S-1-5-21-1085031214-1801674531-725345543-11553' ist ein LCM-Methodenaufruf eingegangen.
[WebAdaptorHost]: LCM:  [ StartenFestlegen]
[WebAdaptorHost]: LCM:  [ StartenRessource]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall]
[WebAdaptorHost]: LCM:  [ StartenTesten   ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall]
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Vorgang "CIM-Instanzen aufzählen" mit den folgenden Parametern durchführen, "'namespaceName' = root\cimv2,'className' = Win32_Product".
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Vorgang "CIM-Instanzen aufzählen" wurde abgeschlossen.
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Multiple Instances of Web Adaptor are already installed
[WebAdaptorHost]: LCM:  [ BeendenTesten   ]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall]  in 0.5310 Sekunden.
[WebAdaptorHost]: LCM:  [ StartenFestlegen]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall]
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-ManagementConsole
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-ManagementScriptingTools
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-ManagementService
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-ISAPIExtensions
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-ISAPIFilter
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-RequestFiltering
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-WindowsAuthentication
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-StaticContent
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-ASPNET45
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-NetFxExtensibility45
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Windows Feature: IIS-WebSockets
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Version des Zielabbilds: 10.0.14393.3561
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Installing Software using installer at \\sbd3201\gis\ArcGIS108\WebAdaptorIIS\Setup.exe and arguments /qb VDIRNAME=portal WEBSITE_ID=1
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Giving Permissions to Folders for IIS_IUSRS
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] Increasing Web Request Timeout to 1 hour
[WebAdaptorHost]:                            [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall] In Set-Resource for
[WebAdaptorHost]: LCM:  [ BeendenFestlegen]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall]  in 62.5300 Sekunden.
[WebAdaptorHost]: LCM:  [ BeendenRessource]  [[ArcGIS_WebAdaptorInstall]WebAdaptorInstall]
[WebAdaptorHost]: LCM:  [ StartenRessource]  [[ArcGIS_WebAdaptor]ConfigurePortal-WebAdaptorHost.domain.com]
[WebAdaptorHost]: LCM:  [ StartenTesten   ]  [[ArcGIS_WebAdaptor]ConfigurePortal-WebAdaptorHost.domain.com]
[WebAdaptorHost]: LCM:  [ BeendenTesten   ]  [[ArcGIS_WebAdaptor]ConfigurePortal-WebAdaptorHost.domain.com]  in 0.1090 Sekunden.
[WebAdaptorHost]: LCM:  [ BeendenFestlegen]
Vorgang "CIM-Methode aufrufen" wurde abgeschlossen.
```

**Comment by scma-esrich** [comment] 2020-04-09 10:16
@shailesh91 and @cameronkroeker: May it be that the "/qb"-parameter is causing the problem, with an alert-window popping up?

**Comment by scma-esrich** [comment] 2020-04-15 06:45
@shailesh91 and @cameronkroeker: Ignore my last two posts.
The situation resolved itself:
The issue was caused by version 3.0.0 of the repository, in more detail the missing update of the "alias"- to the "CNameFQDN"-parameter in the sample-configs. This lead to a mix of the JSON-config-parameter and what the module expected.
